create table pessoas (
    id int8 generated by default as identity, 
    nome varchar(80), 
    tipo_pessoa char(1), 
    cpf_cnpj varchar(14),
    data_nascimento Date,
    observacao varchar(255),
    primary key (id)
);