create table enderecos (
    id int8 generated by default as identity, 
	pessoa_id int8,
	bairro_id int8,
	logradouro_id int8,
    nome varchar(80), 
    numero int8, 
    complemento varchar(40),
	taxa decimal(10,2) ,
    status varchar(20),
    cadastro  timestamp not null ,
	alteracao  timestamp ,
    primary key (id)
);

create table bairros (
    id int8 generated by default as identity, 
    nome varchar(80), 
    primary key (id)
);

create table logradouros (
    id int8 generated by default as identity, 
	tipo_logradouro varchar(20),
    nome varchar(80), 
	complemento varchar(40),
    primary key (id)
);

alter table enderecos add constraint fk_enderecos_ref_pessoas foreign key(pessoa_id) references pessoas(id);
alter table enderecos add constraint fk_enderecos_ref_bairros foreign key(bairro_id) references bairros(id);
alter table enderecos add constraint fk_enderecos_ref_logradouro foreign key(logradouro_id) references logradouros(id);