create table correspondencias (
    id int8 generated by default as identity, 
	endereco_id int8,
	tipo_correspondecia varchar(40), 
    descricao varchar(40),
    data_registro  timestamp not null,
    primary key (id)
);
alter table correspondencias add constraint fk_correspon_ref_enderecos foreign key(endereco_id) references enderecos(id);